flyway.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
flyway.user=postgres.iigncewhrgwdokmkjldx
flyway.password=cuerco01203
flyway.locations=filesystem:/flyway/sql
flyway.defaultSchema=public
flyway.encoding=UTF-8
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.connectRetries=3
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
